devel/hs-haskell-language-server: Update to 1.4.0
freebsd/freebsd-ports-haskell pull request #44
Opened 2021-09-17 12:33 UTC by alexDarcy

Ghc-api-compat is now managed as a "normal" dependency.
Added tasty & co. as dependencies.

2021-09-19 08:03 UTC, arrowd requested changes
Can you please change the commit message to just "devel/hs-haskell-language-server: Update to 1.4.0" ?

2021-09-19 08:03 UTC, arrowd commented on devel/hs-haskell-language-server/Makefile
>  	${MV} ${WRKSRC}/stack-8.10.5.yaml ${WRKSRC}/stack-8.10.7.yaml
This line isn't needed anymore too.

2021-09-19 20:30 UTC, alexDarcy commented
I've applied your suggestions, thanks.

2021-09-20 08:36 UTC, merged

2021-09-20 08:39 UTC, arrowd commented
Thanks for update for this complex port!